name: Cl

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 60

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download Playit agent
      run: |
        $url = "https://github.com/playit-cloud/playit-agent/releases/download/v0.16.2/playit-windows-x86_64-signed.exe"
        Invoke-WebRequest -Uri $url -OutFile playit.exe

    - name: Enable RDP and firewall
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

    - name: Create local user
      shell: powershell
      run: |
        $username = "admin"
        $passwordPlain = "Letmein123!"   # must meet Windows complexity rules
        $securePass = ConvertTo-SecureString $passwordPlain -AsPlainText -Force

        if (-not (Get-LocalUser -Name $username -ErrorAction SilentlyContinue)) {
          New-LocalUser -Name $username -Password $securePass -FullName $username -Description "RDP user"
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member $username
        } else {
          Set-LocalUser -Name $username -Password $securePass
        }

    - name: Run Playit agent (prints claim URL)
      shell: powershell
      run: |
        Write-Host "Starting Playit agent. Watch logs below for the claim URL."
        .\playit.exe
